### DISCUSSION TITLE
Allow usage of server variables other than default

### DISCUSSION THREAD

**Discussion by meesvandongen** [Kong/insomnia#4183] [Ideas]
**Is your feature request related to a problem? Please describe.**
I would like to generate a Kong Configuration for multiple servers using the same OpenAPI specification file.

**Describe the solution you'd like**
OpenAPI allows specifying "server variables" in the servers field of the specification. These are currently set to the default value by openapi-2-kong. I would propose adding a new command line option to the CLI for specifying these server variables. 

**Describe alternatives you've considered**
Writing a script to replace these variables in the generated config, perhaps substituting with another templating system so it doesn't interfere with `openapi-2-kong`. 

**Additional context**
An example of a server variable in OpenAPI
```yaml
{
  "servers": [
    {
      "url": "https://{username}.gigantic-server.com:{port}/{basePath}",
      "description": "The production API server",
      "variables": {
        "username": {
          "default": "demo",
          "description": "this value is assigned by the service provider, in this example `gigantic-server.com`"
        },
        "port": {
          "enum": [
            "8443",
            "443"
          ],
          "default": "8443"
        },
        "basePath": {
          "default": "v2"
        }
      }
    }
  ]
}
```
