### DISCUSSION TITLE
OpenAPI import description from servers

### DISCUSSION THREAD

**Discussion by karlismelderis-mckinsey** [Kong/insomnia#5824] [Ideas]
at the moment Request collection from OpenAPI looks rather chatty
<img width="291" alt="Screenshot 2023-03-06 at 15 58 52" src="https://user-images.githubusercontent.com/112691050/223148258-4e04431b-c06a-497e-a273-7abf1e6843da.png">

we're deleting and re-importing latest API spec
our descriptions for servers are much more usable than FQDN:
```yaml
servers:
  - url: https://prod.exmaple.com/api
    description: Production
  - url: https://dev.example.com/api
    description: Dev
  - url: http://localhost:8088/api
    description: Local
```

hence using description instead of `Use OpenAPI env ...long FQDN...` hurts UX
