### ISSUE TITLE
[Bug] Extracting substring to token value doesn't reference tag properly

### ISSUE THREAD

**Issue by ronkot** [Kong/insomnia#1809]
I'd need to chain certain requests. In the middle of the chain I'd need to parse a substring from a response JSON field and use that value in the next step. I couldn't find out way to do this. Is it possible somehow?

Example:

Response body

```json
{
  "url": "https://redirect.to?code=abc123"
}
```

And I'd like to extract the `code` query param value from the `$.url` field.

**Comment by gschier** [comment]
You'll have to store the response value in a temporary environment variable first.

For example:

```json
{
  "url": "<RESPONSE TAG>",
  "code": "{{ url | replace('https://redirect.to?code=', '') }}"
}
```

Is this for OAuth 2.0? If so, have you tried using Insomnia's built-in OAuth 2.0 support?

**Comment by ronkot** [comment]
Thanks @gschier, nice idea 👍 I tried this approach but unfortunately it doesn't work fully. When I create the temporary `code` environment variable in _Manage Environments_, the extracted code value seems ok. But when I use the `code` environment value in a request, the value that gets injected is the original url (not the extracted code). I try to play around more to see if it's just PEBKAC.

> Is this for OAuth 2.0? If so, have you tried using Insomnia's built-in OAuth 2.0 support?

Yes it is. I tried also the built-in OAuth 2.0 flow, but unfortunately it seems that our OAuth flow does not fully follow the standard (shame). Hopefully we'll get that fixed in the future!

**Comment by ronkot** [comment]
I tried to debug my configuration but couldn't make it work. Tested that when I change the `url` environment variable to be a string constant everything works as expected. But when I use the response tag method you suggested the `code` environment value that is used in request is plain url value. Looks like the the replace filters are not run for response tags.

Could this be a problem in insomnia?

**Comment by gschier** [comment]
Okay, I just reproduce this. Posting a reproducible export here for reference:

```yaml
_type: export
__export_format: 4
__export_date: 2019-12-04T16:21:51.929Z
__export_source: insomnia.desktop.app:v7.0.5
resources:
  - _id: req_b0143e610dab46d0aa03e1432f5d07f3
    authentication: {}
    body:
      mimeType: application/json
      text: |-
        {
        	"code": "https://foo.com?code=123"
        }
    created: 1575475382554
    description: ""
    headers:
      - id: pair_4b04cbadf968438bb2a9562f52d22ed7
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1575475382555
    method: POST
    modified: 1575476270125
    name: Fetch Code
    parameters: []
    parentId: wrk_829e722180014fc48c533233625a5001
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: https://api.insomnia.rest/mock/echo
    _type: request
  - _id: wrk_829e722180014fc48c533233625a5001
    created: 1568746602246
    description: ""
    modified: 1568746602246
    name: Dummy
    parentId: null
    _type: workspace
  - _id: req_d3dc450285624296a8d6bc81b825a556
    authentication: {}
    body: {}
    created: 1575476271209
    description: ""
    headers: []
    isPrivate: false
    metaSortKey: -1575259926047
    method: POST
    modified: 1575476313784
    name: Use Code
    parameters:
      - description: ""
        id: pair_057a1d50893e40918ce694ad5cc0f526
        name: foo
        value: "{{ code  }}"
    parentId: wrk_829e722180014fc48c533233625a5001
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: https://api.insomnia.rest/mock/echo?code={{code}}
    _type: request
  - _id: env_da3efe009b9bb4d300bac075d1004d6c81fc472e
    color: null
    created: 1568746602281
    data: {}
    dataPropertyOrder: null
    isPrivate: false
    metaSortKey: 1568746602281
    modified: 1568746602281
    name: Base Environment
    parentId: wrk_829e722180014fc48c533233625a5001
    _type: environment
  - _id: env_38af930fb18749cb9ff25eded75c3f40
    color: null
    created: 1575476174748
    data:
      code: "{{ url | replace('https://foo.com?code=', '') }}"
      url: "{% response 'body', 'req_b0143e610dab46d0aa03e1432f5d07f3',
        'b64::JC5jb2Rl::46b', 'never' %}"
    isPrivate: false
    metaSortKey: 1575476174748
    modified: 1575476242447
    name: Testing
    parentId: env_da3efe009b9bb4d300bac075d1004d6c81fc472e
    _type: environment
```
